apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - react
      containers:
      - name: react-app
        image: db-proj-react-app
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort  # To access externally
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
