apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "4000"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nodejs
      containers:
      - name: nodejs-app
        image: db-proj-node-app
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_HOST
            value: "postgres"
          - name: DB_USER
            value: "mahdi"
          - name: DB_PASSWORD
            value: "1234"
          - name: DB_NAME
            value: "bank"
          - name: DB_PORT
            value: "5432"
        ports:
          - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP